CREATE DATABASE IF NOT EXISTS nsxtools;
CREATE TABLE IF NOT EXISTS nsxmanagers (id INT(11) NOT NULL, type VARCHAR(25) NOT NULL, ip VARCHAR(45) NOT NULL, username VARCHAR(45) NOT NULL, password VARCHAR(100) NOT NULL, created DATETIME, lastmodified DATETIME, PRIMARY KEY (id));
